"""Initial Migration

Revision ID: 07ebfd66de60
Revises: 
Create Date: 2021-02-25 13:40:03.962266

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
import pgadapter.models

revision = '07ebfd66de60'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pg_dataset',
                    sa.Column('id', pgadapter.models.GUID(), autoincrement=False, nullable=False),
                    sa.Column('table_name', sa.String(length=256), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pg_dataset')
    # ### end Alembic commands ###
